### ISSUE TITLE
Issue with abs/fabs in Ubuntu 18.04

### ISSUE THREAD

**Issue by ehkropf** [ehkropf/ModifiedSchwarz#24]
I changed this as g++ 7.2.0 (with wasn't the case with 5.4) was returning abs(-ve number) as zero and hence solutions for points inside the domain were being returned as NaN.

I think in the current code, the standard abs is being called, not arma::abs? Using arma::abs returns a type error since the expression contains doubles. I'll re-look at the details sometime this week anyway. 

(OS tested on = Ubuntu 18.04).

_Originally posted by @rhodrin in https://github.com/ehkropf/ModifiedSchwarz/commit/ce66f939cf0d3609b3c4099f3435705e50c5651b#commitcomment-31084877_

**Comment by rhodrin** [comment]
Note that changing `abs` to `arma::abs` [here](https://github.com/ehkropf/ModifiedSchwarz/blob/master/src/UnitCircleDomain.cpp#L54) results in a compile error: `error: no matching function for call to ‘abs(std::complex<double>)’`.

**Comment by ehkropf** [comment]
Curious. It must be then getting called from somewhere with a simple (non-arma) complex value. I'll see if I can chase this down.

**Comment by ehkropf** [comment]
@rhodrin, I can compile on Ubuntu 18.04 without this error (but see #25!!!). What libraries do you have installed? (Can you do `dpkg -l`? And the version numbers of any packages not installed via apt?)

**Comment by rhodrin** [comment]
Apt installed:-
cmake 3.10.2
g++ 7.3.0
LAPACK 3.7.1
Open BLAS 0.2.20
ARPACK 3.5.0
ATLAS - Seems to be missing!?

Non apt installed:-
Armadillo: 7.950.1
SuperLU: 5.2.1

My system was upgraded from 16.04, so it maybe that some conflict or something has arisen during the upgrade.

**Comment by ehkropf** [comment]
I'd say first try to re-install armadillo. I'm using v9 right now, but the v8 (now supplied in universal repository) should also work. Everything else looks good. ATLAS doesn't seem to be needed (older armadillo install doc?); it's not on my 18.04 install. I need to remove it from the README.

**Comment by ehkropf** [comment]
Turns out this was my fault. I should have used `std::abs` here. Fixed in commit 936b2ddb. (Currently dev branch.)
